#!/bin/bash

export TERM=xterm-256color

printf '\e[0;32m'
cat<<'TF'
 _            _
| | _____  __| |_ __ ___
| |/ / _ \/ _` | '__/ _ \
|   <  __/ (_| | | | (_) |
|_|\_\___|\__,_|_|  \___/

TF

printf '\e[m'